/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.wanli.guicedemo;

import org.junit.Test;

import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Date;
import java.util.Properties;

public class AppTest {
    @Test
    public void testAppHasAGreeting() throws MessagingException {
        Properties props = new Properties();
        props.put("mail.transport.protocol", "smtp");
        //发件人的邮箱smtp服务器地址
        props.put("mail.smtp.host", "smtp.office365.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.ssl.enable", "true");

        Session session = Session.getInstance(props);

        MimeMessage message = new MimeMessage(session);
        //发件人
        message.setFrom(new InternetAddress("wanlinus@qq.com"));
        //subject
        message.setSubject("subject", "UTF-8");
        //正文
        message.setContent("正文", "text/html;charset=UTF-8");
        message.setSentDate(new Date());
        message.saveChanges();

        Transport transport = session.getTransport();
        transport.connect("wanlinustaylor@outlook.com", "15520734733!");
        transport.sendMessage(message, message.getAllRecipients());
        transport.close();

    }
}
